### ISSUE TITLE
[Question] How to mimic WGCNA's TOMsimilarity functionality?

### ISSUE THREAD

**Issue by jolespin** [benmaier/GTOM#3]
The parameters for `gtom` are different than `TOMsimilarity` from `WGCNA`.  How can I adjust  the parameters of `gtom`?  I always preprocess my adjacency matrix and only use the default settings of `TOMsimilarity`, basically, how do I know which values to input for: `numSteps` and `indices` to mimic the functionality above. 

```
TOMsimilarity(
    adjMat,
    TOMType = "unsigned",
    TOMDenom = "min",
    suppressTOMForZeroAdjacencies = FALSE,
    suppressNegativeTOM = FALSE,
    useInternalMatrixAlgebra = FALSE,
    verbose = 1,
    indent = 0)
```
https://rdrr.io/cran/WGCNA/man/TOMsimilarity.html

**Comment by benmaier** [comment]
Hi! Sorry, I have neither used the WGCNA package nor do I actually still apply GTOM, so I'm a bit rusty on the details. if you want to compute the TOM from the original Ravasz-paper then `numSteps = 1`, (nearest neighbor overlap) for the more general method people seem to use `numSteps = 2` (second-nearest neighbor overlap). `indices` refers to the node indices for which you want to calculate similarities to all other nodes. I've implemented this because I've applied GTOM to huge adjacency matrices. with `indices` you can split the computations to save memory. it's alright to just not provide this keyword if you want to get the whole similarity matrix. For more details I suggest you dig further in the WGCNA docs and also read the original publication:

Gene network interconnectedness and the generalized topological overlap measure, A. M. Yip and S. Horvath, BMC Bioinformatics 2007 8:22

Sorry that I can't be of much help here.

**Comment by jolespin** [comment]
Ah no worries, thanks for getting back to me so quickly.  `numSteps=1` seems like it would do the trick but the outputs are different for some reason.  It looks like the WGCNA version pushes everything in between 0 and 1.

**Comment by benmaier** [comment]
can you post outputs? my package should actually output values between 0 and 1, as well. which `gtom` version are you using? v0.5?

**Comment by jolespin** [comment]
There's no `__version__` attribute so I'm not sure which version is being used but my pip installation was from this github and it says its version 0.5

Here's a way to reproduce to data:

```python
from sklearn.datasets import load_iris
from gtom import gtom
import scipy.sparse as sprs

def get_iris_data():
    iris = load_iris()
    # Iris dataset
    X = pd.DataFrame(iris.data,
                     index = [*map(lambda x:f"iris_{x}", range(150))],
                     columns = [*map(lambda x: x.split(" (cm)")[0].replace(" ","_"), iris.feature_names)])

    y = pd.Series(iris.target,
                           index = X.index,
                           name = "Species")
    return X, y

# Get data
X, y = get_iris_data()

# Create an adjacency network
A_adj = np.abs(X.T.corr().values)

print("Input: ADJ", "Max: {}".format(A_adj.ravel().max()), "Min: {}".format(A_adj.ravel().min()), sep="\n")
sprs_adj = sprs.csr_matrix(A_adj)
A_tom = gtom(sprs_adj, numSteps=1).todense()
print("\nOutput: TOM", "Max: {}".format(A_tom.ravel().max()), "Min: {}".format(A_tom.ravel().min()), sep="\n")

# WGCNA
A_tom_wgcna = # WGCNA's TOM
print("\nOutput: TOM(WGCNA)", "Max: {}".format(A_tom_wgcna.ravel().max()), "Min: {}".format(A_tom_wgcna.ravel().min()), sep="\n")

# Input: ADJ
# Max: 1.0
# Min: 0.35739643082771205

# Output: TOM
# Max: 1.0134228187919463
# Min: 0.9914114890566544

# Output: TOM(WGCNA)
# Max: 1.0
# Min: 0.7375900051201467
```

**Comment by benmaier** [comment]
is this a weighted network?

**Comment by benmaier** [comment]
follow up: the usage of `X.T.corr()` implies that you're using a correlation matrix as a network which has non-binary entries. `gtom` is actually only implemented for unweighted, undirected networks (it says so in the `README.md` but I should probably make this more prominent). I don't know which algorithm `WGCNA` uses but using a weighted adjacency matrix in `gtom` will likely give you wrong results.

**Comment by jolespin** [comment]
Yea, it’s from correlations.

**Comment by benmaier** [comment]
okay, I just found out how WGCNA computes the TOM, they're simply using the weighted adjacency in in the formula (see http://dibernardo.tigem.it/files/papers/2008/zhangbin-statappsgeneticsmolbio.pdf). For performance reasons I coded the algorithm for binary adjacency matrices only so unfortunately the package does not seem to be the right choice for your problem. Apologies! I don't plan to implement this either because I don't have time, so I'm closing this as "wontfix".

**Comment by jolespin** [comment]
Thanks for actually taking a look at this!  I appreciate it a lot.  I tried reading their code but its C and very confusing.  I will let you know if I find a way to adapt this.  Does this seem to be the weighted version:

![image](https://user-images.githubusercontent.com/9061708/59392651-47d99f80-8d2d-11e9-8845-d95b6bceafec.png)

**Comment by jolespin** [comment]
I tried the following but I can't seem to get it to work...

```python
A = A_adj.copy()
dimensions = A.shape
assert dimensions[0] == dimensions[1]
d = dimensions[0]

np.fill_diagonal(A, 0)

A_tom = np.zeros_like(A)
for i in range(d):
    a_iu = A[i]
    k_i = a_iu.sum()
    for j in range(i+1, d):
        a_ju = A[:,j]
        k_j = a_ju.sum()
        l_ij = np.dot(a_iu, a_ju)
        a_ij = A[i,j]
        numerator = l_ij + a_ij
        denominator = min(k_i, k_j) + 1 - a_ij
        w_ij = numerator/denominator
        A_tom[i,j] = w_ij
A_tom = (A_tom + A_tom.T)
```

**Comment by benmaier** [comment]
I believe your code should be correct from what I infer from the paper. Here's some shorter code achieving the same thing:

```python
L = A.dot(A.T)
ki = A.sum(axis=1)
kj = A.sum(axis=0)
MINK = np.array([ np.minimum(ki_,kj) for ki_ in ki ])
A_tom = (L+A) / (MINK + 1 - A)
np.fill_diagonal(A_tom,1)
```

I don't know where any differences would arise
